site_name: HTTPX
site_description: A next-generation HTTP client for Python.
site_url: https://www.python-httpx.org/

theme:
    name: 'material'
    features:
        - navigation.sections

repo_name: encode/httpx
repo_url: https://github.com/encode/httpx/
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - Usage:
        - QuickStart: 'quickstart.md'
        - Advanced Usage: 'advanced.md'
    - Guides:
        - Async Support: 'async.md'
        - HTTP/2 Support: 'http2.md'
        - Requests Compatibility: 'compatibility.md'
        - Troubleshooting: 'troubleshooting.md'
    - API Reference:
        - Developer Interface: 'api.md'
        - Exceptions: 'exceptions.md'
        - Environment Variables: 'environment_variables.md'
    - Community:
        - Third Party Packages: 'third_party_packages.md'
        - Contributing: 'contributing.md'
        - Code of Conduct: 'code_of_conduct.md'

markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight
  - mkautodoc

extra_css:
    - css/custom.css

extra_javascript:
  - 'js/chat.js'
  - 'js/sidecar-1.5.0.js'
